# Generated by Django 6.0.1 on 2026-02-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="user_name",
            new_name="username",
        ),
    ]
